import type { Chapter } from '@/types/content';
import { chapterOutlines } from '@/content/chapter-outlines';

const chapter = (
  id: string,
  slug: string,
  order: number,
  title: string,
  summary: string,
  level: Chapter['level'],
  taskTypes: string[],
  options: Partial<
    Pick<Chapter, 'prerequisiteIds' | 'takeaways' | 'hasContent'>
  > = {},
): Chapter => ({
  id,
  slug,
  order,
  title,
  summary,
  level,
  taskTypes,
  prerequisiteIds: options.prerequisiteIds ?? [],
  outline: chapterOutlines[id],
  takeaways: options.takeaways ?? [],
  hasContent: options.hasContent ?? false,
});

export const chapters: Chapter[] = [
  chapter(
    'ch-01',
    'how-to-read',
    1,
    'Як читати олімпіадну задачу',
    'Виділяємо дані, ціль, умови та приховані зв’язки.',
    'foundation',
    ['пряма реалізація', 'аналіз умови'],
    {
      takeaways: [
        'Переписати умову мовою даних та операцій.',
        'Відокремити гарантовані властивості від прикладів.',
        'Сформулювати, що саме має повернути алгоритм.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-02',
    'constraints-complexity',
    2,
    'Constraints і оцінка складності',
    'Перекладаємо обмеження на допустиму асимптотику.',
    'foundation',
    ['оцінка складності'],
    {
      prerequisiteIds: ['ch-01'],
      takeaways: [
        'Оцінити допустимий клас складності за розміром входу.',
        'Врахувати всі параметри та помітити маленький параметр.',
        'Оцінити не лише час, а й обсяг пам’яті.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-03',
    'brute-force-to-efficient',
    3,
    'Від brute force до ефективного алгоритму',
    'Будуємо просте рішення та знаходимо зайву роботу.',
    'foundation',
    ['оптимізація', 'повний перебір'],
    {
      prerequisiteIds: ['ch-02'],
      takeaways: [
        'Сформулювати правильне brute-force рішення.',
        'Знайти операцію, що виконується повторно.',
        'Замінити перебір preprocessing, структурою даних або новою моделлю.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-04',
    'recognize-pattern',
    4,
    'Як розпізнати патерн і перевірити рішення',
    'Формуємо гіпотезу, доведення та набір перевірок.',
    'foundation',
    ['розпізнавання патернів'],
    {
      prerequisiteIds: ['ch-01', 'ch-02'],
      takeaways: [
        'Пов’язати властивості задачі з алгоритмічними кандидатами.',
        'Перевірити ключову передумову обраного патерну.',
        'Спробувати зламати рішення контрприкладом до написання коду.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-05',
    'cpp-stl',
    5,
    'C++ та STL для олімпіадного програмування',
    'Практичний набір інструментів для швидкої реалізації.',
    'foundation',
    ['реалізація', 'контейнери'],
    {
      takeaways: [
        'Безпечно працювати з числовими типами та уникати overflow.',
        'Використовувати vector, sorting і binary search у STL.',
        'Вибирати контейнер за потрібними операціями та їх складністю.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-06',
    'implementation-arrays-strings',
    6,
    'Implementation, масиви та рядки',
    'Проходи по масивах і рядках, симуляція та частоти. Не кожна задача приховує складний алгоритм: часто достатньо точно прочитати умову й акуратно підтримувати стан.',
    'foundation',
    ['масиви', 'рядки'],
    {
      prerequisiteIds: ['ch-01', 'ch-02', 'ch-05'],
      takeaways: [
        'Підтримувати відповідь і поточну серію за один прохід.',
        'Виділяти мінімальний стан симуляції та перевіряти межі.',
        'Перетворювати значення на частоти й правильно обробляти рівність.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-07',
    'sorting-basic-data-structures',
    7,
    'Сортування та базові структури даних',
    'Сортування змінює структуру задачі й часто залишає лише локальні порівняння. Для контейнерів діє інше просте правило: спочатку потрібні операції, потім інструмент.',
    'foundation',
    ['сортування', 'структури даних'],
    {
      prerequisiteIds: ['ch-05', 'ch-06'],
      takeaways: [
        'Доводити, коли після сортування достатньо сусідніх елементів.',
        'Записувати кілька критеріїв у коректний comparator.',
        'Вибирати vector, set, map або priority_queue за потрібними операціями.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-08',
    'prefix-suffix-preprocessing',
    8,
    'Prefix, Suffix та Preprocessing',
    'Precompute once → answer many times. Один раз рахуємо потрібну інформацію, щоб швидко відповідати на запити або відкласти масові зміни до фінального проходу.',
    'foundation',
    ['відрізки', 'багато запитів'],
    {
      prerequisiteIds: ['ch-02', 'ch-06'],
      takeaways: [
        'Побачити повторне обчислення тієї самої інформації.',
        'Побудувати префіксний стан і правильно визначити його межі.',
        'Використовувати Prefix Sum / Count, Difference Array і 2D Prefix; розрізняти prefix та suffix.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-09',
    'basic-math-invariants',
    9,
    'Базова математика, спостереження та інваріанти',
    'Математична властивість може повністю прибрати потребу в переборі чи симуляції. Шукаємо періоди, спільні дільники, інваріанти та прості формули.',
    'foundation',
    ['математика', 'інваріанти'],
    {
      prerequisiteIds: ['ch-02', 'ch-03', 'ch-06'],
      takeaways: [
        'Замінювати циклічний процес формулою з modulo.',
        'Використовувати GCD, LCM та решето й оцінювати переповнення.',
        'Доводити інваріанти, розрізняти необхідність і достатність, знаходити MEX.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-10',
    'two-pointers-sliding-window',
    10,
    'Two Pointers та Sliding Window',
    'Підтримуємо рухоме вікно без повторної роботи.',
    'core',
    ['підмасиви', 'відрізки'],
    {
      prerequisiteIds: ['ch-06', 'ch-07', 'ch-08'],
      takeaways: [
        'Рухати дві межі лише вперед і доводити, які кандидати відкидаються.',
        'Підтримувати суму або частоти поточного sliding window без повторного підрахунку.',
        'Розрізняти задачу про пару, неперервний відрізок і range query.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-11',
    'binary-search',
    11,
    'Search Techniques',
    'Шукаємо межу допустимих значень і досліджуємо простір відповіді.',
    'core',
    ['пошук', 'оптимізація'],
    {
      prerequisiteIds: ['ch-02', 'ch-07'],
      takeaways: [
        'Безпечно працювати з lower_bound, upper_bound та межами binary search.',
        'Перетворювати оптимізацію на монотонну перевірку can(X).',
        'Розпізнавати Minimize Maximum / Maximize Minimum і доводити greedy-check.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-12',
    'greedy-constructive',
    12,
    'Greedy та Constructive Algorithms',
    'Робимо локальний вибір або будуємо потрібний об’єкт.',
    'core',
    ['вибір', 'побудова'],
    {
      prerequisiteIds: ['ch-04', 'ch-07'],
      takeaways: [
        'Доводити greedy через exchange argument, а не лише інтуїцію.',
        'Вибирати правильний порядок для інтервалів та перевіряти модель їх меж.',
        'Будувати конструкцію блоками й окремо доводити випадки неможливості.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-13',
    'stack-queue-monotonic',
    13,
    'Stack, Queue та Monotonic Structures',
    'Підтримуємо потрібний порядок елементів онлайн.',
    'core',
    ['стек', 'черга'],
    {
      prerequisiteIds: ['ch-05', 'ch-06', 'ch-10'],
      takeaways: [
        'Вибирати stack, queue або deque за потрібним порядком доступу.',
        'Знаходити nearest greater / smaller монотонним стеком за O(n).',
        'Підтримувати minimum або maximum кожного вікна монотонною чергою.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-14',
    'graphs',
    14,
    'Графи',
    'Моделюємо зв’язки, маршрути та досяжність.',
    'combination',
    ['графи', 'маршрути'],
  ),
  chapter(
    'ch-15',
    'trees-dsu-mst',
    15,
    'Дерева, DSU та MST',
    'Працюємо з ієрархіями, компонентами та каркасами.',
    'combination',
    ['дерева', 'компоненти'],
  ),
  chapter(
    'ch-16',
    'dynamic-programming',
    16,
    'Dynamic Programming',
    'Зберігаємо відповіді для станів і будуємо переходи.',
    'combination',
    ['оптимізація', 'підрахунок способів'],
  ),
  chapter(
    'ch-17',
    'queries-data-structures',
    17,
    'Запити та структури даних',
    'Обробляємо багато запитів і змін даних.',
    'combination',
    ['запити', 'оновлення'],
  ),
  chapter(
    'ch-18',
    'string-algorithms',
    18,
    'String Algorithms',
    'Шукаємо збіги, періоди та структуру тексту.',
    'advanced',
    ['рядки', 'пошук'],
  ),
  chapter(
    'ch-19',
    'computational-geometry',
    19,
    'Computational Geometry',
    'Перетворюємо геометричні умови на точні обчислення.',
    'advanced',
    ['координати', 'геометрія'],
  ),
  chapter(
    'ch-20',
    'small-n-bitmask-mitm',
    20,
    'Small-n, Bitmask та Meet in the Middle',
    'Використовуємо малий параметр замість великого n.',
    'advanced',
    ['малий n', 'підмножини'],
  ),
  chapter(
    'ch-21',
    'advanced-graphs-trees',
    21,
    'Advanced Graphs та Trees',
    'Поєднуємо структуру графа з ефективними запитами.',
    'advanced',
    ['графи', 'дерева'],
  ),
  chapter(
    'ch-22',
    'probability-combinatorics-math',
    22,
    'Probability, Combinatorics та Advanced Math',
    'Рахуємо конфігурації та працюємо з випадковістю.',
    'advanced',
    ['математика', 'комбінаторика'],
  ),
  chapter(
    'ch-23',
    'matching-flow',
    23,
    'Matching та Flow',
    'Моделюємо призначення, пропускні здатності та розподіл.',
    'challenge',
    ['зв’язки', 'розподіл'],
  ),
  chapter(
    'ch-24',
    'dp-optimization',
    24,
    'Оптимізація Dynamic Programming',
    'Прискорюємо переходи за допомогою додаткової структури.',
    'challenge',
    ['оптимізація DP'],
  ),
  chapter(
    'ch-25',
    'game-theory',
    25,
    'Game Theory',
    'Шукаємо виграшні стани та правильну модель гри.',
    'challenge',
    ['ігри', 'стани'],
  ),
  chapter(
    'ch-26',
    'reformulation-combination',
    26,
    'Переформулювання та комбінування алгоритмів',
    'Змінюємо погляд на задачу, коли готового патерну не видно.',
    'challenge',
    ['переформулювання', 'комбінація'],
  ),
];
