import type { Chapter } from '@/types/content';
import { chapterOutlines } from '@/content/chapter-outlines';

const chapter = (
  id: string,
  slug: string,
  order: number,
  title: string,
  summary: string,
  level: Chapter['level'],
  taskTypes: string[],
  options: Partial<
    Pick<Chapter, 'prerequisiteIds' | 'takeaways' | 'hasContent'>
  > = {},
): Chapter => ({
  id,
  slug,
  order,
  title,
  summary,
  level,
  taskTypes,
  prerequisiteIds: options.prerequisiteIds ?? [],
  outline: chapterOutlines[id],
  takeaways: options.takeaways ?? [],
  hasContent: options.hasContent ?? false,
});

export const chapters: Chapter[] = [
  chapter(
    'ch-01',
    'how-to-read',
    1,
    'Як читати олімпіадну задачу',
    'Виділяємо дані, ціль, умови та приховані зв’язки.',
    'foundation',
    ['пряма реалізація', 'аналіз умови'],
    {
      takeaways: [
        'Переписати умову мовою даних та операцій.',
        'Відокремити гарантовані властивості від прикладів.',
        'Сформулювати, що саме має повернути алгоритм.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-02',
    'constraints-complexity',
    2,
    'Constraints і оцінка складності',
    'Перекладаємо обмеження на допустиму асимптотику.',
    'foundation',
    ['оцінка складності'],
    {
      prerequisiteIds: ['ch-01'],
      takeaways: [
        'Оцінити допустимий клас складності за розміром входу.',
        'Врахувати всі параметри та помітити маленький параметр.',
        'Оцінити не лише час, а й обсяг пам’яті.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-03',
    'brute-force-to-efficient',
    3,
    'Від brute force до ефективного алгоритму',
    'Будуємо просте рішення та знаходимо зайву роботу.',
    'foundation',
    ['оптимізація', 'повний перебір'],
    {
      prerequisiteIds: ['ch-02'],
      takeaways: [
        'Сформулювати правильне brute-force рішення.',
        'Знайти операцію, що виконується повторно.',
        'Замінити перебір preprocessing, структурою даних або новою моделлю.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-04',
    'recognize-pattern',
    4,
    'Як розпізнати патерн і перевірити рішення',
    'Формуємо гіпотезу, доведення та набір перевірок.',
    'foundation',
    ['розпізнавання патернів'],
    {
      prerequisiteIds: ['ch-01', 'ch-02'],
      takeaways: [
        'Пов’язати властивості задачі з алгоритмічними кандидатами.',
        'Перевірити ключову передумову обраного патерну.',
        'Спробувати зламати рішення контрприкладом до написання коду.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-05',
    'cpp-stl',
    5,
    'C++ та STL для олімпіадного програмування',
    'Практичний набір інструментів для швидкої реалізації.',
    'foundation',
    ['реалізація', 'контейнери'],
    {
      takeaways: [
        'Безпечно працювати з числовими типами та уникати overflow.',
        'Використовувати vector, sorting і binary search у STL.',
        'Вибирати контейнер за потрібними операціями та їх складністю.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-06',
    'implementation-arrays-strings',
    6,
    'Implementation, масиви та рядки',
    'Проходи по масивах і рядках, симуляція та частоти. Не кожна задача приховує складний алгоритм: часто достатньо точно прочитати умову й акуратно підтримувати стан.',
    'foundation',
    ['масиви', 'рядки'],
    {
      prerequisiteIds: ['ch-01', 'ch-02', 'ch-05'],
      takeaways: [
        'Підтримувати відповідь і поточну серію за один прохід.',
        'Виділяти мінімальний стан симуляції та перевіряти межі.',
        'Перетворювати значення на частоти й правильно обробляти рівність.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-07',
    'sorting-basic-data-structures',
    7,
    'Сортування та базові структури даних',
    'Сортування змінює структуру задачі й часто залишає лише локальні порівняння. Для контейнерів діє інше просте правило: спочатку потрібні операції, потім інструмент.',
    'foundation',
    ['сортування', 'структури даних'],
    {
      prerequisiteIds: ['ch-05', 'ch-06'],
      takeaways: [
        'Доводити, коли після сортування достатньо сусідніх елементів.',
        'Записувати кілька критеріїв у коректний comparator.',
        'Вибирати vector, set, map або priority_queue за потрібними операціями.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-08',
    'prefix-suffix-preprocessing',
    8,
    'Prefix, Suffix та Preprocessing',
    'Precompute once → answer many times. Один раз рахуємо потрібну інформацію, щоб швидко відповідати на запити або відкласти масові зміни до фінального проходу.',
    'foundation',
    ['відрізки', 'багато запитів'],
    {
      prerequisiteIds: ['ch-02', 'ch-06'],
      takeaways: [
        'Побачити повторне обчислення тієї самої інформації.',
        'Побудувати префіксний стан і правильно визначити його межі.',
        'Використовувати Prefix Sum / Count, Difference Array і 2D Prefix; розрізняти prefix та suffix.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-09',
    'basic-math-invariants',
    9,
    'Базова математика, спостереження та інваріанти',
    'Математична властивість може повністю прибрати потребу в переборі чи симуляції. Шукаємо періоди, спільні дільники, інваріанти та прості формули.',
    'foundation',
    ['математика', 'інваріанти'],
    {
      prerequisiteIds: ['ch-02', 'ch-03', 'ch-06'],
      takeaways: [
        'Замінювати циклічний процес формулою з modulo.',
        'Використовувати GCD, LCM та решето й оцінювати переповнення.',
        'Доводити інваріанти, розрізняти необхідність і достатність, знаходити MEX.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-10',
    'two-pointers-sliding-window',
    10,
    'Two Pointers та Sliding Window',
    'Підтримуємо рухоме вікно без повторної роботи.',
    'core',
    ['підмасиви', 'відрізки'],
    {
      prerequisiteIds: ['ch-06', 'ch-07', 'ch-08'],
      takeaways: [
        'Рухати дві межі лише вперед і доводити, які кандидати відкидаються.',
        'Підтримувати суму або частоти поточного sliding window без повторного підрахунку.',
        'Розрізняти задачу про пару, неперервний відрізок і range query.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-11',
    'binary-search',
    11,
    'Search Techniques',
    'Шукаємо межу допустимих значень і досліджуємо простір відповіді.',
    'core',
    ['пошук', 'оптимізація'],
    {
      prerequisiteIds: ['ch-02', 'ch-07'],
      takeaways: [
        'Безпечно працювати з lower_bound, upper_bound та межами binary search.',
        'Перетворювати оптимізацію на монотонну перевірку can(X).',
        'Розпізнавати Minimize Maximum / Maximize Minimum і доводити greedy-check.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-12',
    'greedy-constructive',
    12,
    'Greedy та Constructive Algorithms',
    'Робимо локальний вибір або будуємо потрібний об’єкт.',
    'core',
    ['вибір', 'побудова'],
    {
      prerequisiteIds: ['ch-04', 'ch-07'],
      takeaways: [
        'Доводити greedy через exchange argument, а не лише інтуїцію.',
        'Вибирати правильний порядок для інтервалів та перевіряти модель їх меж.',
        'Будувати конструкцію блоками й окремо доводити випадки неможливості.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-13',
    'stack-queue-monotonic',
    13,
    'Stack, Queue та Monotonic Structures',
    'Підтримуємо потрібний порядок елементів онлайн.',
    'core',
    ['стек', 'черга'],
    {
      prerequisiteIds: ['ch-05', 'ch-06', 'ch-10'],
      takeaways: [
        'Вибирати stack, queue або deque за потрібним порядком доступу.',
        'Знаходити nearest greater / smaller монотонним стеком за O(n).',
        'Підтримувати minimum або maximum кожного вікна монотонною чергою.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-14',
    'graphs',
    14,
    'Графи',
    'Моделюємо зв’язки, маршрути та досяжність.',
    'combination',
    ['графи', 'маршрути'],
    {
      prerequisiteIds: ['ch-04', 'ch-13'],
      takeaways: [
        'Перетворювати клітинки, об’єкти та стани на вершини й ребра.',
        'Вибирати shortest-path алгоритм за типом ваг.',
        'Працювати із залежностями через DAG і topological order.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-15',
    'trees-dsu-mst',
    15,
    'Дерева, DSU та MST',
    'Працюємо з ієрархіями, компонентами та каркасами.',
    'combination',
    ['дерева', 'компоненти'],
    {
      prerequisiteIds: ['ch-07', 'ch-14'],
      takeaways: [
        'Вкорінювати дерево й перетворювати піддерево на Euler-відрізок.',
        'Підтримувати компоненти, що об’єднуються, через DSU.',
        'Відрізняти MST від shortest path і будувати Kruskal.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-16',
    'dynamic-programming',
    16,
    'Dynamic Programming',
    'Зберігаємо відповіді для станів і будуємо переходи.',
    'combination',
    ['оптимізація', 'підрахунок способів'],
    {
      prerequisiteIds: ['ch-03', 'ch-08', 'ch-14', 'ch-15'],
      takeaways: [
        'Формулювати state реченням до запису transition.',
        'Вибирати base cases, порядок обчислення та місце відповіді.',
        'Переносити DP на рюкзак, таблицю, рядки, DAG і дерево.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-17',
    'queries-data-structures',
    17,
    'Запити та структури даних',
    'Обробляємо багато запитів і змін даних.',
    'combination',
    ['запити', 'оновлення'],
    {
      prerequisiteIds: ['ch-08', 'ch-13', 'ch-15'],
      takeaways: [
        'Вибирати структуру даних за точним набором update/query операцій.',
        'Працювати з Fenwick і Segment Tree за O(log n).',
        'Переформульовувати offline-запити через compression, порядок або рухоме вікно.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-18',
    'string-algorithms',
    18,
    'String Algorithms',
    'Шукаємо збіги, періоди та структуру тексту.',
    'advanced',
    ['рядки', 'пошук'],
    {
      prerequisiteIds: ['ch-06', 'ch-08', 'ch-11'],
      takeaways: [
        'Будувати prefix function і Z-function та застосовувати їх до пошуку й періодів.',
        'Порівнювати підрядки хешами, явно контролюючи колізії та індекси.',
        'Вибирати рядковий алгоритм за тим, яку саме інформацію про збіги повертає задача.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-19',
    'computational-geometry',
    19,
    'Computational Geometry',
    'Перетворюємо геометричні умови на точні обчислення.',
    'advanced',
    ['координати', 'геометрія'],
    {
      prerequisiteIds: ['ch-07', 'ch-09', 'ch-12'],
      takeaways: [
        'Перекладати повороти, належність і перетини у знаки cross product.',
        'Коректно обробляти колінеарність, межі відрізків і цілочисельну точність.',
        'Будувати convex hull та використовувати його як компактну оболонку множини точок.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-20',
    'small-n-bitmask-mitm',
    20,
    'Small-n, Bitmask та Meet in the Middle',
    'Використовуємо малий параметр замість великого n.',
    'advanced',
    ['малий n', 'підмножини'],
    {
      prerequisiteIds: ['ch-02', 'ch-03', 'ch-16'],
      takeaways: [
        'Кодувати вибір підмножини бітовою маскою та безпечно перебирати маски й підмаски.',
        'Проєктувати Bitmask DP, де mask є достатнім описом уже виконаних рішень.',
        'Ділити експоненційний пошук навпіл через Meet in the Middle.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-21',
    'advanced-graphs-trees',
    21,
    'Advanced Graphs та Trees',
    'Поєднуємо структуру графа з ефективними запитами.',
    'advanced',
    ['графи', 'дерева'],
    {
      prerequisiteIds: ['ch-14', 'ch-15', 'ch-16', 'ch-17'],
      takeaways: [
        'Стискати орієнтований граф у DAG компонент сильної зв’язності та знаходити критичні ребра й вершини.',
        'Відповідати на ancestor/LCA-запити за допомогою binary lifting.',
        'Перераховувати відповіді для всіх коренів і зливати інформацію піддерев без квадратичної роботи.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-22',
    'probability-combinatorics-math',
    22,
    'Probability, Combinatorics та Advanced Math',
    'Рахуємо конфігурації та працюємо з випадковістю.',
    'advanced',
    ['математика', 'комбінаторика'],
    {
      prerequisiteIds: ['ch-09', 'ch-16', 'ch-20'],
      takeaways: [
        'Рахувати комбінаторні об’єкти та застосовувати Inclusion–Exclusion без подвійного підрахунку.',
        'Будувати expectation через індикатори й лінійність математичного сподівання.',
        'Розв’язувати модульні рівняння та прискорювати лінійні переходи матричним піднесенням до степеня.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-23',
    'matching-flow',
    23,
    'Matching та Flow',
    'Моделюємо призначення, пропускні здатності та розподіл.',
    'challenge',
    ['зв’язки', 'розподіл'],
    {
      prerequisiteIds: ['ch-14', 'ch-15', 'ch-21'],
      takeaways: [
        'Розпізнавати assignment як bipartite matching і перебудовувати рішення augmenting paths.',
        'Пояснювати residual graph та реалізовувати Dinic для maximum flow.',
        'Будувати й доводити flow/min-cut reductions, включно з vertex capacities і costs.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-24',
    'dp-optimization',
    24,
    'Оптимізація Dynamic Programming',
    'Прискорюємо переходи за допомогою додаткової структури.',
    'challenge',
    ['оптимізація DP'],
    {
      prerequisiteIds: ['ch-16', 'ch-17', 'ch-19'],
      takeaways: [
        'Знаходити структуру argmin і застосовувати Divide & Conquer Optimization лише після доведення monotonicity.',
        'Перевіряти строгі умови Knuth замість орієнтації лише на форму recurrence.',
        'Перетворювати DP-transition на line queries та вибирати між monotone CHT і Li Chao Tree.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-25',
    'game-theory',
    25,
    'Game Theory',
    'Шукаємо виграшні стани та правильну модель гри.',
    'challenge',
    ['ігри', 'стани'],
    {
      prerequisiteIds: ['ch-09', 'ch-14', 'ch-16', 'ch-20'],
      takeaways: [
        'Класифікувати winning/losing states як DP на state graph.',
        'Доводити zero-XOR invariant Nim і відновлювати виграшний хід.',
        'Обчислювати Grundy numbers та XOR-комбінувати незалежні impartial games.',
      ],
      hasContent: true,
    },
  ),
  chapter(
    'ch-26',
    'reformulation-combination',
    26,
    'Переформулювання та комбінування алгоритмів',
    'Змінюємо погляд на задачу, коли готового патерну не видно.',
    'challenge',
    ['переформулювання', 'комбінація'],
    {
      prerequisiteIds: ['ch-17', 'ch-20', 'ch-21', 'ch-23', 'ch-24', 'ch-25'],
      takeaways: [
        'Будувати implicit state graph із мінімальним достатнім станом.',
        'Перетворювати deletions на additions через reverse time та застосовувати rollback.',
        'Розкладати capstone-задачу на representation, decomposition і data structure та доводити їхні interfaces.',
      ],
      hasContent: true,
    },
  ),
];
