import type { ProblemTypeGroup } from '@/types/content';

export const problemTypeGroups: ProblemTypeGroup[] = [
  {
    id: 'implementation',
    title: 'Пряма реалізація та обробка даних',
    description: 'Симуляція, індекси, порядок дій і базові контейнери.',
    topics: [
      'Implementation',
      'Arrays / Strings',
      'Sorting',
      'STL',
      'Prefix / Preprocessing',
      'Базова математика',
    ],
    chapterIds: ['ch-06', 'ch-07', 'ch-08', 'ch-09'],
  },
  {
    id: 'segments',
    title: 'Підмасиви, підрядки та відрізки',
    description: 'Задачі про неперервні частини послідовності.',
    topics: [
      'Prefix Sum',
      'Two Pointers',
      'Sliding Window',
      'Kadane',
      'Monotonic Structures',
      'Fenwick / Segment Tree',
    ],
    chapterIds: ['ch-08', 'ch-10', 'ch-13', 'ch-16', 'ch-17'],
  },
  {
    id: 'optimization',
    title: 'Мінімум, максимум та оптимізація',
    description: 'Пошук найкращого значення або структури.',
    topics: [
      'Sorting',
      'Greedy',
      'Binary Search on Answer',
      'Ternary Search',
      'DP',
      'DP Optimization',
    ],
    chapterIds: ['ch-07', 'ch-11', 'ch-12', 'ch-16', 'ch-24'],
  },
  {
    id: 'construct',
    title: 'Вибір, розподіл та побудова',
    description: 'Локальні рішення, призначення та конструктив.',
    topics: [
      'Greedy',
      'Constructive',
      'Knapsack',
      'Matching',
      'Flow',
      'Combinatorics',
    ],
    chapterIds: ['ch-12', 'ch-16', 'ch-22', 'ch-23'],
  },
  {
    id: 'counting',
    title: 'Підрахунок кількості способів',
    description: 'Стани, комбінаторика та правила підрахунку.',
    topics: [
      'Dynamic Programming',
      'Combinatorics',
      'Bitmask DP',
      'Inclusion–Exclusion',
      'Probability',
    ],
    chapterIds: ['ch-16', 'ch-20', 'ch-22'],
  },
  {
    id: 'queries',
    title: 'Багато запитів або змін даних',
    description: 'Попередня обробка й структури для швидких відповідей.',
    topics: [
      'Prefix',
      'Sparse Table',
      'Fenwick Tree',
      'Segment Tree',
      'Sqrt Decomposition',
      'Mo’s Algorithm',
      'Offline Processing',
    ],
    chapterIds: ['ch-08', 'ch-17'],
  },
  {
    id: 'connections',
    title: 'Зв’язки, маршрути та залежності',
    description: 'Графові моделі, досяжність і потоки.',
    topics: [
      'BFS / DFS',
      'Shortest Paths',
      'DAG',
      'DSU / MST',
      'SCC',
      '2-SAT',
      'Matching / Flow',
    ],
    chapterIds: ['ch-14', 'ch-15', 'ch-21', 'ch-23'],
  },
  {
    id: 'hierarchies',
    title: 'Ієрархії та дерева',
    description: 'Піддерева, накопичення інформації та запити на деревах.',
    topics: [
      'Trees',
      'Tree DP',
      'Euler Tour',
      'LCA',
      'Rerooting',
      'HLD',
      'Small-to-Large',
      'Centroid Decomposition',
    ],
    chapterIds: ['ch-15', 'ch-16', 'ch-21'],
  },
  {
    id: 'small-parameter',
    title: 'Малий n або малий параметр',
    description: 'Експонента стає прийнятною завдяки малому параметру.',
    topics: [
      'Brute Force',
      'Bitmask',
      'Bitmask DP',
      'Meet in the Middle',
      'Parameterized Techniques',
    ],
    chapterIds: ['ch-20'],
  },
  {
    id: 'numbers',
    title: 'Числа, формули та математика',
    description: 'Властивості чисел, формули та комбінаторні моделі.',
    topics: [
      'Number Theory',
      'MEX',
      'Modular Arithmetic',
      'Combinatorics',
      'Matrix Exponentiation',
      'Probability',
      'Advanced Math',
    ],
    chapterIds: ['ch-09', 'ch-22'],
  },
  {
    id: 'strings',
    title: 'Рядки',
    description: 'Підрядки, збіги, частоти та структура тексту.',
    topics: [
      'Basic String Processing',
      'Two Pointers',
      'KMP / Z',
      'Hashing',
      'Trie',
      'Manacher',
      'Aho-Corasick',
      'Suffix Array',
    ],
    chapterIds: ['ch-06', 'ch-10', 'ch-18'],
  },
  {
    id: 'geometry',
    title: 'Координати та геометрія',
    description: 'Точки, вектори та просторові відношення.',
    topics: [
      'Sorting',
      'Geometry',
      'Sweep Line',
      'Binary Search',
      'Number Theory',
    ],
    chapterIds: ['ch-07', 'ch-09', 'ch-11', 'ch-19', 'ch-22'],
  },
  {
    id: 'logic',
    title: 'Логічні умови та сумісність',
    description: 'Чи можна узгодити вимоги, зв’язки та призначення?',
    topics: ['Bipartite Graph', '2-SAT', 'Matching', 'Flow', 'DSU'],
    chapterIds: ['ch-14', 'ch-15', 'ch-21', 'ch-23'],
  },
  {
    id: 'hidden',
    title: 'Алгоритм не видно',
    description:
      'Спостереження й зміна моделі замість пошуку готового рецепта.',
    topics: [
      'Observation',
      'Invariants',
      'Constructive',
      'Contribution Technique',
      'Algebraic Transformation',
      'Переформулювання задачі',
      'Комбінування алгоритмів',
    ],
    chapterIds: ['ch-09', 'ch-12', 'ch-26'],
  },
];
